// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: google.proto

package google

import (
	meta "github.com/vedadiyan/proton/tests/google/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoCompleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *meta.Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Input  string       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *AutoCompleteReq) Reset() {
	*x = AutoCompleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoCompleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompleteReq) ProtoMessage() {}

func (x *AutoCompleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompleteReq.ProtoReflect.Descriptor instead.
func (*AutoCompleteReq) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{0}
}

func (x *AutoCompleteReq) GetClient() *meta.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AutoCompleteReq) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type NearbyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client    *meta.Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Latitude  float64      `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64      `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *NearbyReq) Reset() {
	*x = NearbyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyReq) ProtoMessage() {}

func (x *NearbyReq) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyReq.ProtoReflect.Descriptor instead.
func (*NearbyReq) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyReq) GetClient() *meta.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *NearbyReq) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyReq) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client         *meta.Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	PhotoReference string       `protobuf:"bytes,2,opt,name=photoReference,json=photo_reference,proto3" json:"photoReference,omitempty"`
}

func (x *ImageReq) Reset() {
	*x = ImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageReq) ProtoMessage() {}

func (x *ImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageReq.ProtoReflect.Descriptor instead.
func (*ImageReq) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{2}
}

func (x *ImageReq) GetClient() *meta.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ImageReq) GetPhotoReference() string {
	if x != nil {
		return x.PhotoReference
	}
	return ""
}

type Prediction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	PlaceId     string `protobuf:"bytes,2,opt,name=placeId,json=place_id,proto3" json:"placeId,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{3}
}

func (x *Prediction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Prediction) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Prediction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Photos    []string `protobuf:"bytes,3,rep,name=photos,proto3" json:"photos,omitempty"`
	PlaceId   string   `protobuf:"bytes,4,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Rating    float64  `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Result) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Result) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Result) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Result) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ArrayOfPredictions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prediction []*Prediction `protobuf:"bytes,1,rep,name=prediction,proto3" json:"prediction,omitempty"`
}

func (x *ArrayOfPredictions) Reset() {
	*x = ArrayOfPredictions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayOfPredictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayOfPredictions) ProtoMessage() {}

func (x *ArrayOfPredictions) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayOfPredictions.ProtoReflect.Descriptor instead.
func (*ArrayOfPredictions) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{5}
}

func (x *ArrayOfPredictions) GetPrediction() []*Prediction {
	if x != nil {
		return x.Prediction
	}
	return nil
}

type ArrayOfResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ArrayOfResults) Reset() {
	*x = ArrayOfResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayOfResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayOfResults) ProtoMessage() {}

func (x *ArrayOfResults) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayOfResults.ProtoReflect.Descriptor instead.
func (*ArrayOfResults) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{6}
}

func (x *ArrayOfResults) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type AutoCompleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*AutoCompleteRes_Data
	//	*AutoCompleteRes_Error
	Result isAutoCompleteRes_Result `protobuf_oneof:"result"`
}

func (x *AutoCompleteRes) Reset() {
	*x = AutoCompleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoCompleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoCompleteRes) ProtoMessage() {}

func (x *AutoCompleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoCompleteRes.ProtoReflect.Descriptor instead.
func (*AutoCompleteRes) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{7}
}

func (m *AutoCompleteRes) GetResult() isAutoCompleteRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *AutoCompleteRes) GetData() *ArrayOfPredictions {
	if x, ok := x.GetResult().(*AutoCompleteRes_Data); ok {
		return x.Data
	}
	return nil
}

func (x *AutoCompleteRes) GetError() *meta.Error {
	if x, ok := x.GetResult().(*AutoCompleteRes_Error); ok {
		return x.Error
	}
	return nil
}

type isAutoCompleteRes_Result interface {
	isAutoCompleteRes_Result()
}

type AutoCompleteRes_Data struct {
	Data *ArrayOfPredictions `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type AutoCompleteRes_Error struct {
	Error *meta.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AutoCompleteRes_Data) isAutoCompleteRes_Result() {}

func (*AutoCompleteRes_Error) isAutoCompleteRes_Result() {}

type NearbyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*NearbyRes_Results
	//	*NearbyRes_Error
	Result isNearbyRes_Result `protobuf_oneof:"result"`
}

func (x *NearbyRes) Reset() {
	*x = NearbyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NearbyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyRes) ProtoMessage() {}

func (x *NearbyRes) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyRes.ProtoReflect.Descriptor instead.
func (*NearbyRes) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{8}
}

func (m *NearbyRes) GetResult() isNearbyRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *NearbyRes) GetResults() *ArrayOfResults {
	if x, ok := x.GetResult().(*NearbyRes_Results); ok {
		return x.Results
	}
	return nil
}

func (x *NearbyRes) GetError() *meta.Error {
	if x, ok := x.GetResult().(*NearbyRes_Error); ok {
		return x.Error
	}
	return nil
}

type isNearbyRes_Result interface {
	isNearbyRes_Result()
}

type NearbyRes_Results struct {
	Results *ArrayOfResults `protobuf:"bytes,1,opt,name=results,proto3,oneof"`
}

type NearbyRes_Error struct {
	Error *meta.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*NearbyRes_Results) isNearbyRes_Result() {}

func (*NearbyRes_Error) isNearbyRes_Result() {}

type ImageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*ImageRes_Image
	//	*ImageRes_Error
	Result isImageRes_Result `protobuf_oneof:"result"`
}

func (x *ImageRes) Reset() {
	*x = ImageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRes) ProtoMessage() {}

func (x *ImageRes) ProtoReflect() protoreflect.Message {
	mi := &file_google_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRes.ProtoReflect.Descriptor instead.
func (*ImageRes) Descriptor() ([]byte, []int) {
	return file_google_proto_rawDescGZIP(), []int{9}
}

func (m *ImageRes) GetResult() isImageRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ImageRes) GetImage() []byte {
	if x, ok := x.GetResult().(*ImageRes_Image); ok {
		return x.Image
	}
	return nil
}

func (x *ImageRes) GetError() *meta.Error {
	if x, ok := x.GetResult().(*ImageRes_Error); ok {
		return x.Error
	}
	return nil
}

type isImageRes_Result interface {
	isImageRes_Result()
}

type ImageRes_Image struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3,oneof"`
}

type ImageRes_Error struct {
	Error *meta.Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ImageRes_Image) isImageRes_Result() {}

func (*ImageRes_Error) isImageRes_Result() {}

var file_google_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51234,
		Name:          "select",
		Tag:           "bytes,51234,opt,name=select",
		Filename:      "google.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51235,
		Name:          "query",
		Tag:           "bytes,51235,opt,name=query",
		Filename:      "google.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string select = 51234;
	E_Select = &file_google_proto_extTypes[0]
	// optional string query = 51235;
	E_Query = &file_google_proto_extTypes[1]
)

var File_google_proto protoreflect.FileDescriptor

var file_google_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x6d, 0x65, 0x74, 0x61, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x22, 0x6b, 0x0a, 0x09, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x24, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x22, 0x59, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xa1, 0x01, 0x0a,
	0x0a, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0f, 0x92, 0x82, 0x19, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0c, 0x92, 0x82, 0x19, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x23, 0x92, 0x82, 0x19, 0x1f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x82, 0x02, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x42, 0x19, 0x92,
	0x82, 0x19, 0x15, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x61, 0x74, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x42, 0x19, 0x92, 0x82, 0x19, 0x15, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x6e, 0x67,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x42, 0x23, 0x9a, 0x82, 0x19,
	0x1f, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x28, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x2c, 0x20,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x29,
	0x52, 0x06, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0x92, 0x82, 0x19, 0x08,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x42, 0x0a, 0x92, 0x82, 0x19, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x52, 0x0a, 0x12, 0x41, 0x72, 0x72, 0x61, 0x79, 0x4f, 0x66,
	0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0f, 0x92, 0x82,
	0x19, 0x0b, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x0e, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0b, 0x92, 0x82, 0x19, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x6b, 0x0a, 0x0f, 0x41,
	0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x29,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x4f, 0x66, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x67, 0x0a, 0x09, 0x4e, 0x65, 0x61, 0x72,
	0x62, 0x79, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x4f, 0x66,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x51, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0xca, 0x01, 0x0a, 0x0e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x41, 0x70, 0x69, 0x12, 0x39, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x6f, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10,
	0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x36, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x10, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x4e, 0x65,
	0x61, 0x72, 0x62, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0a, 0x2e, 0x4e, 0x65, 0x61,
	0x72, 0x62, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52,
	0x65, 0x73, 0x12, 0x1d, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x09, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x3a, 0x3a, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa2, 0x90, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x88, 0x01, 0x01, 0x3a, 0x38, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa3, 0x90, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x61, 0x75, 0x74, 0x6f, 0x67,
	0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_proto_rawDescOnce sync.Once
	file_google_proto_rawDescData = file_google_proto_rawDesc
)

func file_google_proto_rawDescGZIP() []byte {
	file_google_proto_rawDescOnce.Do(func() {
		file_google_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_proto_rawDescData)
	})
	return file_google_proto_rawDescData
}

var file_google_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_google_proto_goTypes = []interface{}{
	(*AutoCompleteReq)(nil),           // 0: AutoCompleteReq
	(*NearbyReq)(nil),                 // 1: NearbyReq
	(*ImageReq)(nil),                  // 2: ImageReq
	(*Prediction)(nil),                // 3: Prediction
	(*Result)(nil),                    // 4: Result
	(*ArrayOfPredictions)(nil),        // 5: ArrayOfPredictions
	(*ArrayOfResults)(nil),            // 6: ArrayOfResults
	(*AutoCompleteRes)(nil),           // 7: AutoCompleteRes
	(*NearbyRes)(nil),                 // 8: NearbyRes
	(*ImageRes)(nil),                  // 9: ImageRes
	(*meta.Client)(nil),               // 10: meta.Client
	(*meta.Error)(nil),                // 11: meta.Error
	(*descriptorpb.FieldOptions)(nil), // 12: google.protobuf.FieldOptions
}
var file_google_proto_depIdxs = []int32{
	10, // 0: AutoCompleteReq.client:type_name -> meta.Client
	10, // 1: NearbyReq.client:type_name -> meta.Client
	10, // 2: ImageReq.client:type_name -> meta.Client
	3,  // 3: ArrayOfPredictions.prediction:type_name -> Prediction
	4,  // 4: ArrayOfResults.results:type_name -> Result
	5,  // 5: AutoCompleteRes.data:type_name -> ArrayOfPredictions
	11, // 6: AutoCompleteRes.error:type_name -> meta.Error
	6,  // 7: NearbyRes.results:type_name -> ArrayOfResults
	11, // 8: NearbyRes.error:type_name -> meta.Error
	11, // 9: ImageRes.error:type_name -> meta.Error
	12, // 10: select:extendee -> google.protobuf.FieldOptions
	12, // 11: query:extendee -> google.protobuf.FieldOptions
	0,  // 12: GooglePlaceApi.AutoCompleteAirport:input_type -> AutoCompleteReq
	0,  // 13: GooglePlaceApi.AutoCompleteCity:input_type -> AutoCompleteReq
	1,  // 14: GooglePlaceApi.NearbySearch:input_type -> NearbyReq
	2,  // 15: GooglePlaceApi.Image:input_type -> ImageReq
	7,  // 16: GooglePlaceApi.AutoCompleteAirport:output_type -> AutoCompleteRes
	7,  // 17: GooglePlaceApi.AutoCompleteCity:output_type -> AutoCompleteRes
	8,  // 18: GooglePlaceApi.NearbySearch:output_type -> NearbyRes
	9,  // 19: GooglePlaceApi.Image:output_type -> ImageRes
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	10, // [10:12] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_google_proto_init() }
func file_google_proto_init() {
	if File_google_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoCompleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prediction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayOfPredictions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayOfResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoCompleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NearbyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_google_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*AutoCompleteRes_Data)(nil),
		(*AutoCompleteRes_Error)(nil),
	}
	file_google_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*NearbyRes_Results)(nil),
		(*NearbyRes_Error)(nil),
	}
	file_google_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ImageRes_Image)(nil),
		(*ImageRes_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 2,
			NumServices:   1,
		},
		GoTypes:           file_google_proto_goTypes,
		DependencyIndexes: file_google_proto_depIdxs,
		MessageInfos:      file_google_proto_msgTypes,
		ExtensionInfos:    file_google_proto_extTypes,
	}.Build()
	File_google_proto = out.File
	file_google_proto_rawDesc = nil
	file_google_proto_goTypes = nil
	file_google_proto_depIdxs = nil
}
